---
title: "[Fail Log] 차가운 실패가 무기력한 나날보다는 낫다."
date: 2022-09-13 22:36:00 +0900
categories: failLog
classes: wide
---

## 일기 update (짧게 기록) 
1. 네이버 파이넨셜 이력 결과 -> 서류에서 탈락, 어차피 안될 줄을 알았지만 막상 그렇다고 마음이 안아픈건 아니야. 그러나 지금의 나에게 차가운 실패가 무기력한 나날보다는 낫다.
2. AlgorithmWithJava -> 3장 까지 어찌 어찌 완료, 진도가 너무 늦다
3. pandas_with_stock 부활, 이걸 다시 복기 하려면 얼마나의 시간이 들까.
4. 땀을 너무 많이 흘린다. 체중의 문제 -> 헬스장을 등록, 3개월의 33만원, 먼저 공부 후 10시 ~ 11시 사이에 헬스장에서 간단히 운동을 한다. 운동을 못하면 샤워라도 한다.
5. 맨탈관리, 피지컬관리, 결국 내가 하기에 따름 -> 도서관 61번 사물한 86일 간 사용하기로, 여기 사물함이 헬스장 사물함보다 크다.
6. 이번주 토요일 바빌론 오픈 : 드디어 sbi가 끝이난다. 떨어지는 낙엽도 조심
7. 블로그 배포를 부활 시켰다. -> 수정 사항 발생 화면 비율 조정 너무 글씨가 크다.

## 블로그 배포에 관하여 
블로그 배포가 안된 것은 Jekyll 배포에 사용되는 _config.yml에 96번째 라인에 키가 빠져 있어서 그랬다.
github는 착하게도 GitHub Pages 서비스로 배포를 할 경우 내 매일로 친절하게 빌드 실패 로그를 쏴준다.

그 로그를 이제야 확인 했다.

```linux
block mapping at line 96 column 13 (Psych::SyntaxError)
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:143:in `safe_load_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:180:in `read_config_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:207:in `block in read_config_files'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:205:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:205:in `read_config_files'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll.rb:113:in `configuration'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/command.rb:43:in `configuration_from_options'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:29:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
  Logging at level: debug
github-pages 227 | Error:  (/github/workspace/./_config.yml): did not find expected key while parsing a block mapping at line 96 column 13
```

> github-pages 227 | Error:  (/github/workspace/./_config.yml): did not find expected key while parsing a block mapping at ***line 96 column 13***

친절하신 github 님과 마이크소프트 님께 감사와 경배를....